# ---------------
# mode: light | dark | auto | time
mode: auto

# é»˜è®¤è¯­è¨€ä¸ºä¸­æ–‡ zh-CNã€‚ç«™ç‚¹çš„è¯­è¨€éœ€è¦è‡ªå·±åœ¨ Hexo ç›®å½•ä¸‹çš„ _config.yml ä¸­è®¾ç½®ã€‚
language: ja

# Theme color for customize
# Notice: color value must in double quotes: "#000000"
colors:
  primary: "#986DB2" # åŠ
  bg: "#F6F7F8" #æœˆç™½
  selection_bg: "#B28FCE" #è–„
  tag_start_color: "#9F353A" #æ¡œ
  tag_end_color: "#0086CC" #å¤©è‰²
  dark:
    block: "#17202A"

# You can set color for every tag or category.
tags:
  Vue: "#4fc08d"
  Hexo: "#0E83CD"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#FC9F4D"
  TypeScript: "#317AC6"

categories:
  ç¬”è®°: dimgray

# Favicon
# ---------------
favicon: /images/favicon.ico

preconnect:
  - https://lib.baomitu.com
  - https://npm.elemecdn.com
  - https://code.bdstatic.com

js:
  - /custom/custom.js

# åŠ è½½è‡ªå®šä¹‰çš„èµ„æº
head:
  css:
    custom: /custom/custom.css
  js:
    async:
      # è¿™é‡Œæ˜¯ä½ ä» iconfont å¤„è·å¾—çš„å›¾æ ‡é“¾æ¥ã€‚
      iconfont: https://at.alicdn.com/t/font_2598701_hm5djhdw3d.js

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Posts / Categories / Tags in sidebar.
sidebar:
  # bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn@master/img/bg/alpha-stars-timing-1.webp
  # bg_image: /images/1.png
  bg_image: https://pic.rmb.bdstatic.com/bjh/events/928b2d243add8479cba157f772639d4b.png
  # dark_bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn@master/img/bg/dark-alpha-stars-timing-1.webp
  # dark_bg_image: /images/1.gif
  dark_bg_image: https://upload-bbs.mihoyo.com/upload/2022/04/04/260511332/59a41e82283e78f82b2dd9ca8eb171c7_2812559093585149692.gif
  bg_position: bottom 1rem center
  # åœ¨ä¾§è¾¹æ æ˜¾ç¤º Hexo åŸç”Ÿæ ‡ç­¾é¡µ
  tagcloud:
    enable: false
    amount: 20

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: No contents.
  collapse: true

# Social Links.
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: Qzone
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://794545154.qzone.qq.com/
    icon: icon-qzone
    color: "#fbce00"
  - name: GitHub
    link: https://github.com/asadahimeka
    icon: icon-github-line
    color: "#6e5494"
  - name: å¾®åš
    link: https://weibo.com/u/2195128415
    icon: icon-weibo-line
    color: "#E6162D"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=73306134
    icon: icon-netease-cloud-music-line
    color: "#C20C0C"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/8051085
    icon: icon-bilibili-line
    color: "#FF8EB3"
  # - name: QQ éŸ³ä¹
  #   link: https://y.qq.com/n/ryqq/profile?uin=7iEP7KvkoK4P
  #   icon: icon-disc-line
  #   color: "#31c27c"
  - name: bangumi
    link: https://bgm.tv/user/234864
    icon: icon-pgc_bangumi
    color: "#F09199"
  - name: é…·å®‰
    link: https://www.coolapk.com/u/496417
    icon: icon-coolapk1
    color: "#0f9d58"
  - name: Instagram
    link: https://www.instagram.com/asadahimeka/
    icon: icon-Instagramlogo
    color: "#FF1F75"
  - name: Twitter
    link: https://twitter.com/soigneehimeka
    icon: icon-twitter-line
    color: "#1da1f2"
  - name: Telegram
    link: https://t.me/himekana
    icon: icon-telegram-line
    color: "#0088CC"
  - name: E-Mail
    link: mailto:sakurayumine@ymail.ne.jp
    icon: icon-mail-line
    color: "#8E71C1"

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

# Extra links
pages:
  - name: Favorite Girls
    url: /girls/
    icon: icon-favorite
    color:
  - name: My Bangumi List
    url: /bangumi/
    icon: icon-zhuiju
    color: "#5db2e6"
  - name: Pixiv Daily Ranking
    url: /illust/pixiv/
    icon: icon-pixiv
    color:
  - name: Konachan Wallpaper
    url: /illust/konachan.html
    icon: icon-tupian1
    color:

# Sidebar Avatar
avatar:
  enable: true
  url: https://dd-static.jd.com/ddimg/jfs/t1/189383/17/25386/40787/6289f448E0afb7904/d5dc07d2ae70bc52.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: true
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1
  # é»˜è®¤å…³é—­ï¼Œå¼€å¯åæ–‡ç« é¡µé¢ä¾§è¾¹æ çš„å¤´åƒå°†å‘ä¸Šç§»åŠ¨ï¼ˆè¿ªå£«å°¼è­¦å‘Šï¼‰
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸŒ 
    message: è¿·ã„è¾¼ã‚“ã 

# main menu navigation
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
  custom:
    title: Albums
    path: /albums/
    icon: icon-gallery-line

# archive
archive:
  last_word: æ²¡æœ‰äº†_(:Ğ·ã€âˆ )_

wordcloud:
  enable: true
  height: 350

# post type
types:
  link:
    color: blue
    icon: icon-external-link-line
  bilibili:
    color: "#FF8EB3"
    icon: icon-bilibili-line
  douban:
    color: "#007722"
    icon: icon-douban-line
  github:
    color: black
    icon: icon-github-line
  netease-cloud-music:
    color: "#C10D0C"
    icon: icon-netease-cloud-music-line
  notion:
    color: black
    icon: icon-notion
  twitter:
    color: "#1da1f2"
    icon: icon-twitter-line
  wechat:
    color: "#1AAD19"
    icon: icon-wechat-2-line
  weibo:
    color: "#E6162D"
    icon: icon-weibo-line
  yuque:
    color: "#25b864"
    icon: icon-yuque
  zhihu:
    color: "#0084FF"
    icon: icon-zhihu-line

# post_card
post_card:
  opacity: 0.9

fireworks:
  enable: true
  colors:
    - "232, 122, 144" # è–„ç´…
    - "255, 177, 27" # å±±å¹
    - "168, 216, 185" # ç™½ç·‘
    - "46, 169, 223" # éœ²è‰

# UI
banner:
  enable: true
  # title: å¬¿æš¶ç’ƒç¦
  # title: ['Hi','me','ka','na']
  title: ãƒ’ãƒ¡ã‚«ãƒŠã®ã‚µã‚¤ãƒˆ
  border: true
  cloud:
    enable: false
    color: "#FEDFE1"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# https://github.com/qrohlf/trianglify
trianglify:
  enable: false
  cell_size: 75
  width: 800
  height: 600
  # https://github.com/qrohlf/trianglify/blob/master/src/utils/colorbrewer.js
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

cursor:
  enable: true
  default: /custom/cursors/pointer.cur
  pointer: /custom/cursors/link.cur
  text: /custom/cursors/text.cur

smoothScroll: true

bg_image:
  enable: true
  # url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg # recomend image related to your mode
  # url: /images/2.png
  # url: https://pic.rmb.bdstatic.com/bjh/events/96f326c7a71260bd68a08d832d57550a.png
  # url: https://pic.rmb.bdstatic.com/bjh/events/660cf2113b0734ea0cc0ce2aeaf13a71.jpeg
  url: https://dd-static.jd.com/ddimg/jfs/t1/206611/25/9501/148838/62a97b7cE39f5852a/c4da5ec9c5e90a65.jpg
  # dark: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/galaxy.jpg
  # dark: /images/8.jpg
  dark: https://upload-bbs.mihoyo.com/upload/2022/04/04/260511332/0cf3ad25832dd5452619a03dfec1f8fb_1110460970989339648.jpg
  # blur: 2px
  opacity: 0.8

# Reward (Donate)
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: false

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.en, deed.ja, etc.
creative_commons: false
  # license: by-nc-sa
  # language: deed.zh
  # post: true
  # clipboard: false

# Post edit
# Dependencies: https://github.com/hexojs/hexo-deployer-git
post_edit:
  enable: false

# Footer Settings
# ---------------
footer:
  since: 2017

  # Icon between year and copyright info.
  icon:
    # `heart` is recommended with animation in red (#ff0000).
    name: icon-heart-line
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#E87A90" # è–„ç´…

  powered:
    # Hexo link (Powered by Hexo).
    enable: true

  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian:
    enable: false
    # icp: è‹ICPå¤‡xxxxxxxxå·

  custom_text: 'Deploys by <a href="https://vercel.com" target="_blank" rel="noopener noreferrer" style=""><svg width="66.33" height="15" viewBox="0 0 283 64" id="vercel-logo" fill="#000" xmlns="http://www.w3.org/2000/svg" style="vertical-align: middle;"><path d="M141.04 16c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.46 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zM248.72 16c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.45 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zM200.24 34c0 6 3.92 10 10 10 4.12 0 7.21-1.87 8.8-4.92l7.68 4.43c-3.18 5.3-9.14 8.49-16.48 8.49-11.05 0-19-7.2-19-18s7.96-18 19-18c7.34 0 13.29 3.19 16.48 8.49l-7.68 4.43c-1.59-3.05-4.68-4.92-8.8-4.92-6.07 0-10 4-10 10zm82.48-29v46h-9V5h9zM36.95 0L73.9 64H0L36.95 0zm92.38 5l-27.71 48L73.91 5H84.3l17.32 30 17.32-30h10.39zm58.91 12v9.69c-1-.29-2.06-.49-3.2-.49-5.81 0-10 4-10 10V51h-9V17h9v9.2c0-5.08 5.91-9.2 13.2-9.2z"></path></svg></a><br><img width="315" height="100" src="https://api.moedog.org/count/@himekana?theme=rule34" style="margin-top:10px" alt>'

  live_time:
    enable: false
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2017-11-02T00:00:00"


# Post meta display settings
post_meta:
  item_text: false # æ˜¯å¦æ˜¾ç¤ºæ–‡å­—ï¼ˆå¦‚ï¼šå‘è¡¨äºã€æ›´æ–°äºï¼Œè‹¥å…³é—­åˆ™åªæ˜¾ç¤ºå›¾æ ‡ä¸æ—¶é—´ä¿¡æ¯ï¼‰
  created_at: true
  updated_at: true
  categories: true
  tags: true

# notice pin board
notice:
  enable: false
  content: Thanks for watching my blog.

# third party
# ----------------

# say something
# https://say.elpsy.cn
say:
  enable: true
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn?c=i

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line

# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: true
  count: true
  time: true

# search
search:
  modal: true
  bg_image: https://pic.rmb.bdstatic.com/bjh/events/71f1378d44d22f1ada01a40944e86013.jpeg
  dark_bg_image: https://upload-bbs.mihoyo.com/upload/2022/04/04/260511332/5f36c9c2ec91bf56caf5331e4ed4918d_4875177930097895211.jpg
  # placeholder: æƒ³è¦æœäº›ä»€ä¹ˆï¼Ÿ

engine_search:
  enable: false
local_search:
  enable: true

# plugins
aplayer:
  global: false
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: false
    autoplay: false
    # theme: "#2980b9"
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: false
    listMaxHeight: 340px
    audio:
      - name: æ˜Ÿå®¿è®¡æ—¶
        artist: æ‰ç”°æœ—/æ´›å¤©ä¾
        url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/audio/star-timer.mp3
        cover: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0.jpg
    meting:
      enable: true
      id: 308168565
      server: netease
      type: playlist

# special
mourn:
  enable: false
  days:
    - "4-4"
    - "5-12"
    - "9-18"
    - "12-13"

girls:
  enable: true

comment:
  enable: true
  icon: icon-chat-3-line
  tips:
    - è¦ä¸è¦å’Œæˆ‘è¯´äº›ä»€ä¹ˆï¼Ÿ
  candidates:
    - waline
    # - giscus

# https://giscus.app/zh-CN
giscus:
  enable: false
  repo: asadahimeka/asadahimeka.vercel.app
  repo-id: R_kgDOHFcTmQ
  category: Announcements
  category-id: DIC_kwDOHFcTmc4CPL39
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# https://waline.js.org/
waline:
  enable: true
  serverURL: https://wlsrv.kanata.ml
  visitor: ".leancloud-visitors-count"
  pageview: ".leancloud-visitors-count"
  comment: true # display comment count
  requiredMeta: ["nick", "mail"]
  wordLimit: 240
  imageUploader: false
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  emoji:
    - https://npm.elemecdn.com/@waline/emojis@1.0.1/weibo/
    - https://npm.elemecdn.com/@waline/emojis@1.0.1/tieba/
    - https://npm.elemecdn.com/@waline/emojis@1.0.1/qq/
    - https://npm.elemecdn.com/@waline/emojis@1.0.1/bilibili/
    - https://npm.elemecdn.com/@waline/emojis@1.0.1/alus/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/åŸç¥Vå®˜æ–¹/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/åŸç¥Vç©å®¶/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/åŸç¥Vå®˜æ–¹-GIF/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/ç±³æ¸¸å…”/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/ç±³æ¸¸å…”-GIF/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©å3Â·é›·é¸£å½»ç©º/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©å3-1/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©å3-1-GIF/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©å3-2/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©å3-2-GIF/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©åRPG/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©åå­¦å›­2/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å´©å2ç©å®¶-GIF/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/å…¬ä¸»è¿ç»“/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/åŒç”Ÿè§†ç•ŒÂ·èŠ±å«/
    - https://npm.elemecdn.com/@himeka/mys_stickers@0.0.3/stickers/æ˜Ÿæ¢¦æ‰‹è®°/


albums:
  enable: true
  icon: icon-gallery-line

anonymous_image: https://upload-bbs.mihoyo.com/upload/2022/04/05/260511332/2035615ec9d3b134ebbb557f674e7fbc_3856836711554332744.jpg

# cdn for third-party library (always include)
cdn:
  css:
    yun-markdown-css: https://npm.elemecdn.com/star-markdown-css@0.2.4/dist/yun/yun-markdown.min.css
    prism-theme-vars: https://npm.elemecdn.com/prism-theme-vars/base.css

# cdn for third-party library (alternative include)
# please see in _vendors.yml
vendors:
  yun-markdown-css: https://npm.elemecdn.com/star-markdown-css@0.2.4/dist/yun/yun-markdown.min.css
  prism-theme-vars: https://npm.elemecdn.com/prism-theme-vars/base.css
  algolia_search: https://lib.baomitu.com/algoliasearch/4.13.0/algoliasearch-lite.umd.min.js
  instant_search: https://lib.baomitu.com/instantsearch.js/4.40.1/instantsearch.production.min.js
  anime: https://lib.baomitu.com/animejs/3.2.1/anime.min.js
  scrollreveal: https://lib.baomitu.com/scrollReveal.js/4.0.9/scrollreveal.min.js
  katex:
    js: https://lib.baomitu.com/KaTeX/0.15.3/katex.min.js
    css: https://lib.baomitu.com/KaTeX/0.15.3/katex.min.css
    auto_render: https://lib.baomitu.com/KaTeX/0.15.3/contrib/auto-render.min.js
    copy_tex:
      css: https://lib.baomitu.com/KaTeX/0.15.3/contrib/copy-tex.min.css
      js: https://lib.baomitu.com/KaTeX/0.15.3/contrib/copy-tex.min.js
  aplayer:
    css: https://lib.baomitu.com/aplayer/1.9.1/APlayer.min.css
    js: https://lib.baomitu.com/aplayer/1.9.1/APlayer.min.js
    meting: https://npm.elemecdn.com/meting@1/dist/Meting.min.js
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/mermaid.min.js
  trianglify: https://lib.baomitu.com/trianglify/3.0.0/trianglify.min.js
  lightgallery:
    css: https://lib.baomitu.com/lightgallery-js/1.4.0/css/lightgallery.min.css
    js: https://lib.baomitu.com/lightgallery-js/1.4.0/js/lightgallery.min.js
  pjax: https://npm.elemecdn.com/pjax@latest/pjax.min.js
  crypto_js:
    all: https://lib.baomitu.com/crypto-js/4.1.1/crypto-js.min.js
  wordcloud: https://lib.baomitu.com/wordcloud2.js/1.2.2/wordcloud2.min.js
  revealjs:
    css: https://lib.baomitu.com/reveal.js/4.3.1/reveal.min.css
    js: https://lib.baomitu.com/reveal.js/4.3.1/reveal.min.js
    plugin:
      markdown: https://lib.baomitu.com/reveal.js/4.3.1/plugin/markdown/markdown.min.js
      notes: https://lib.baomitu.com/reveal.js/4.3.1/plugin/notes/notes.min.js
      highlight:
        js: https://lib.baomitu.com/reveal.js/4.3.1/plugin/highlight/highlight.min.js
        monokai: https://lib.baomitu.com/reveal.js/4.3.1/plugin/highlight/monokai.min.css
  vue: https://lib.baomitu.com/vue/2.6.14/vue.min.js
  darken: https://code.bdstatic.com/npm/darken@1.5.0/dist/darken.umd.js

  # comment
  valine_js: https://cdn.staticfile.org/valine/1.4.18/Valine.min.js
  waline_js: https://cdn.staticfile.org/waline/1.6.0/Waline.min.js
  waline:
    css: https://lib.baomitu.com/waline/2.5.1/waline.min.css
    js: https://lib.baomitu.com/waline/2.5.1/waline.min.js
  minivaline_js: https://npm.elemecdn.com/minivaline@6
  # https://github.com/SukkaW/DisqusJS
  disqusjs:
    css: https://lib.baomitu.com/disqusjs/1.3.0/disqusjs.min.css
    js: https://lib.baomitu.com/disqusjs/1.3.0/disqus.min.js
  twikoo: https://cdn.staticfile.org/twikoo/1.5.1/twikoo.all.min.js
  iconify: https://code.iconify.design/2/2.1.1/iconify.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  unocss:
    runtime: https://npm.elemecdn.com/@unocss/runtime
    core: https://npm.elemecdn.com/@unocss/runtime/core.global.js
    uno: https://npm.elemecdn.com/@unocss/runtime/uno.global.js
    attributify: https://npm.elemecdn.com/@unocss/runtime/attributify.global.js
    mini: https://npm.elemecdn.com/@unocss/runtime/mini.global.js
